### ISSUE TITLE
LVM Partition wiping is not working properly on EL7

### ISSUE THREAD

**Issue by jouvin** [quattor/aii#217]
In EL7, if you reinstall a machine with the same partitions and if there is one partition used by LVM (I think this is the trigger), you have to restart the installer 3 times before the installation proceeds successfully. It may have to do with a message displayed by the installation kernel when it starts about the LVM volume group already existing (if I  saw properly).

It would be a minor problem if the third time it was not necessary to confirme that you want to wipe the LVM logical volumes, as the first 2 reboots occur automatically because the storage configuration doesn't allow the installer to continue.

In fact, there are probably to issues:
- [ ] why wiping doesn't work properly on EL7 when it works well on EL6 (with the same partitioning)?
- [ ] why `-y` is not taken into account by the `lvcreate` command?

**Comment by jrha** [comment]
Discussed at March 2017 workshop, @stdweird suggested that the `-y` option maybe fixed in the install images for 7.3.

**Comment by jrha** [comment]
@gombasg also suggested that the older partition wiping code in blockdevices may be better at eradicting the source of some of these problems.

**Comment by jnovy** [comment]
FYI: we still see lvcreate going interactive without -y in RHEL7u3.

**Comment by jnovy** [comment]
It seems that `-y -Wy -Zy` passed to lvcreate should make the interactivity go away.

[Reference](https://github.com/chef-cookbooks/lvm/issues/45)

**Comment by ned21** [comment]
@stdweird reported that he ran into this 2 weeks ago so it remains a live issue. He will try the options suggested above. @jnovy - how did we solve this internally? Anything we can push upstream?
